#spring.application.name=demo-mybatis
#spring.datasource.url=jdbc:mysql://localhost:3306/mybatis_db?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=mybatis
#spring.datasource.password=mybatis1234

server:
  port: 8080

spring:
  application:
    name: demo-mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: mybatis
    password: mybatis1234